// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiW3wn1TLqw2vOOL1U_AQ_-x7FCoh1R64',
    appId: '1:14098078509:web:f252015b15c712146f11a4',
    messagingSenderId: '14098078509',
    projectId: 'renteasekb',
    authDomain: 'renteasekb.firebaseapp.com',
    storageBucket: 'renteasekb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmKqOj6Z_OPOQfJjwbvq36sxESufCM2d4',
    appId: '1:14098078509:android:d013ac940941cecf6f11a4',
    messagingSenderId: '14098078509',
    projectId: 'renteasekb',
    storageBucket: 'renteasekb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsUUnp0ZV-ZIWf7BmNgc_FQKyVxXX2XYE',
    appId: '1:14098078509:ios:817ae63b2678f3df6f11a4',
    messagingSenderId: '14098078509',
    projectId: 'renteasekb',
    storageBucket: 'renteasekb.appspot.com',
    iosBundleId: 'com.example.renteaseKb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsUUnp0ZV-ZIWf7BmNgc_FQKyVxXX2XYE',
    appId: '1:14098078509:ios:ee23fd12598e92d36f11a4',
    messagingSenderId: '14098078509',
    projectId: 'renteasekb',
    storageBucket: 'renteasekb.appspot.com',
    iosBundleId: 'com.example.renteaseKb.RunnerTests',
  );
}
